# Generated by Django 5.0.6 on 2024-06-21 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('user', '0003_alter_employer_options_alter_jobseeker_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Salary')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('contacts', models.CharField(max_length=13, unique=True, verbose_name='Contacts')),
                ('category', models.ManyToManyField(to='jobs.category', verbose_name='Category')),
                ('company', models.ManyToManyField(to='user.employer', verbose_name='Company')),
                ('experience', models.ManyToManyField(to='jobs.experience', verbose_name='Experience')),
                ('industry', models.ManyToManyField(to='jobs.industry', verbose_name='Industry')),
                ('specializing', models.ManyToManyField(to='jobs.speciality', verbose_name='Speciality')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='Cover letter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='media/resume', verbose_name='Add your resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancy', verbose_name='Choose a vacancy')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='Chosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancy', verbose_name='Choose a vacancy')),
            ],
            options={
                'verbose_name': 'Favourite',
                'verbose_name_plural': 'Favourites',
            },
        ),
    ]
