# Generated by Django 5.0.6 on 2024-06-21 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('industry', models.CharField(blank=True, choices=[('Веб-разработка', 'Веб-разработка'), ('Мобильная разработка', 'Мобильная разработка'), ('Базы данных', 'Базы данных'), ('Кибербезопасность', 'Кибербезопасность'), ('Искусственный интеллект и машинное обучение', 'Искусственный интеллект и машинное обучение'), ('Сетевые технологии', 'Сетевые технологии'), ('IT-консалтинг', 'IT-консалтинг')], max_length=250, null=True, verbose_name='Название отрасли')),
                ('other_industry', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название отрасли(другое)')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('speciality', models.CharField(blank=True, choices=[('Python-разработчик', 'Python-разработчик'), ('JavaScript-разработчик', 'JavaScript-разработчик'), ('Android-разработчик', 'Android-разработчик'), ('iOS-разработчик', 'iOS-разработчик'), ('Специалист по базам данных (DBA)', 'Специалист по базам данных (DBA)'), ('Исследователь данных', 'Исследователь данных'), ('Специалист по безопасности информации (InfoSec)', 'Специалист по безопасности информации (InfoSec)'), ('IT-консультант', 'IT-консультант'), ('Системный администратор', 'Системный администратор')], max_length=255, null=True, verbose_name='Укажите свою специальность ')),
                ('other_speciality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Укажите свою специальность(другое) ')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
            bases=('user.user',),
        ),
    ]
