# Generated by Django 5.0.6 on 2024-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employer_jobseeker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'verbose_name': 'Job seeker', 'verbose_name_plural': 'Job seekers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Name of the company'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, choices=[('Веб-разработка', 'Веб-разработка'), ('Мобильная разработка', 'Мобильная разработка'), ('Базы данных', 'Базы данных'), ('Кибербезопасность', 'Кибербезопасность'), ('Искусственный интеллект и машинное обучение', 'Искусственный интеллект и машинное обучение'), ('Сетевые технологии', 'Сетевые технологии'), ('IT-консалтинг', 'IT-консалтинг')], max_length=250, null=True, verbose_name='Name of the industry'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='other_industry',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the industry(another)'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='other_speciality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Your speciality(another)'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Python-разработчик', 'Python-разработчик'), ('JavaScript-разработчик', 'JavaScript-разработчик'), ('Android-разработчик', 'Android-разработчик'), ('iOS-разработчик', 'iOS-разработчик'), ('Специалист по базам данных (DBA)', 'Специалист по базам данных (DBA)'), ('Исследователь данных', 'Исследователь данных'), ('Специалист по безопасности информации (InfoSec)', 'Специалист по безопасности информации (InfoSec)'), ('IT-консультант', 'IT-консультант'), ('Системный администратор', 'Системный администратор')], max_length=255, null=True, verbose_name='Your speciality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Base user'), (2, 'Moderator')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Employer'), (2, 'Job Seeker')], default=2, verbose_name='Type of the user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
    ]
